"""Build deterministic root-agent adapter plans from one canonical kernel."""

import hashlib
import os
import stat
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

import yaml


CONTROL_PATH = PurePosixPath(".sdd/controls/adapters.yaml")
KERNEL_PATH = PurePosixPath(".sdd/adapters/root-kernel.md")
MANIFEST_PATH = PurePosixPath(".sdd/agent-adapters.generated.json")
RENDERER = "sdd.adapters.agent:v1"

_FORMAT = 1
_MAX_LINES = 280
_TARGET_LINES = 180
_MAX_BYTES = 16384
_OPEN_SUPPORTS_DIR_FD = os.open in os.supports_dir_fd
_OUTPUTS = {"claude": PurePosixPath("CLAUDE.md"), "codex": PurePosixPath("AGENTS.md")}
_PREAMBLES = {
    "claude": (
        b"<!-- Generated root adapter for Claude; do not edit this file directly. -->\n"
        b"<!-- Canonical sources: `.sdd/controls/adapters.yaml` and "
        b"`.sdd/adapters/root-kernel.md`. -->\n\n"
    ),
    "codex": (
        b"<!-- Generated root adapter for Codex; do not edit this file directly. -->\n"
        b"<!-- Canonical sources: `.sdd/controls/adapters.yaml` and "
        b"`.sdd/adapters/root-kernel.md`. -->\n\n"
    ),
}


@dataclass(frozen=True)
class AdapterLimits:
    max_lines: int
    target_lines: int
    max_bytes: int


@dataclass(frozen=True)
class AdapterConfig:
    format: int
    kernel: PurePosixPath
    limits: AdapterLimits
    outputs: tuple[tuple[str, PurePosixPath], ...]


@dataclass(frozen=True)
class AdapterOutput:
    name: str
    target: PurePosixPath
    preamble: bytes
    payload: bytes
    sha256: str
    line_count: int
    byte_count: int


@dataclass(frozen=True)
class AdapterPlan:
    format: int
    renderer: str
    config_sha256: str
    kernel_sha256: str
    outputs: tuple[AdapterOutput, ...]


@dataclass(frozen=True)
class AdapterFinding:
    code: str
    path: PurePosixPath | None
    message: str


class AdapterFailure(Exception):
    def __init__(self, findings: tuple[AdapterFinding, ...]):
        super().__init__("agent adapter planning failed")
        self.findings = findings


def build_adapter_plan(root: Path) -> AdapterPlan:
    """Validate canonical inputs and render both root adapters in memory."""
    try:
        repository = _validated_repository_root(root)
        raw_config = _read_regular_file(repository, CONTROL_PATH)
        config = _load_config(raw_config)
        kernel = _read_regular_file(repository, config.kernel)
        _validate_text_bytes(kernel, "invalid_kernel", config.kernel)
        outputs = _render_outputs(config, kernel)
        return AdapterPlan(
            format=config.format,
            renderer=RENDERER,
            config_sha256=_sha256(raw_config),
            kernel_sha256=_sha256(kernel),
            outputs=outputs,
        )
    except AdapterFailure:
        raise
    except (OSError, RuntimeError, TypeError, ValueError, UnicodeError, yaml.YAMLError):
        raise AdapterFailure(
            (AdapterFinding("technical_block", None, "adapter plan could not be built safely"),)
        ) from None


def _validated_repository_root(root: Path) -> Path:
    repository = Path(root)
    try:
        mode = repository.lstat().st_mode
    except OSError:
        raise AdapterFailure(
            (AdapterFinding("technical_block", None, "repository root is unavailable"),)
        ) from None
    if not stat.S_ISDIR(mode):
        raise AdapterFailure(
            (AdapterFinding("technical_block", None, "repository root is not a safe directory"),)
        )
    return repository


def _read_regular_file(repository: Path, relative: PurePosixPath) -> bytes:
    required_flags = ("O_DIRECTORY", "O_NOFOLLOW", "O_NONBLOCK")
    if not _OPEN_SUPPORTS_DIR_FD or any(not hasattr(os, name) for name in required_flags):
        raise AdapterFailure(
            (
                AdapterFinding(
                    "unsafe_path",
                    relative,
                    "safe descriptor traversal is unavailable",
                ),
            )
        )

    directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
    file_flags = os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK
    close_on_exec = getattr(os, "O_CLOEXEC", 0)
    opened_fds: list[int] = []
    try:
        directory_fd = os.open(repository, directory_flags | close_on_exec)
        opened_fds.append(directory_fd)
        if not stat.S_ISDIR(os.fstat(directory_fd).st_mode):
            raise OSError("unsafe repository root")

        for part in relative.parts[:-1]:
            directory_fd = os.open(
                part,
                directory_flags | close_on_exec,
                dir_fd=directory_fd,
            )
            opened_fds.append(directory_fd)
            if not stat.S_ISDIR(os.fstat(directory_fd).st_mode):
                raise OSError("unsafe canonical parent")

        file_fd = os.open(
            relative.name,
            file_flags | close_on_exec,
            dir_fd=directory_fd,
        )
        opened_fds.append(file_fd)
        if not stat.S_ISREG(os.fstat(file_fd).st_mode):
            raise OSError("unsafe canonical source")
        chunks: list[bytes] = []
        while chunk := os.read(file_fd, 65536):
            chunks.append(chunk)
        return b"".join(chunks)
    except OSError:
        raise AdapterFailure(
            (AdapterFinding("unsafe_path", relative, "canonical source is not a regular file"),)
        ) from None
    finally:
        for opened_fd in reversed(opened_fds):
            os.close(opened_fd)


def _load_config(raw: bytes) -> AdapterConfig:
    _validate_text_bytes(raw, "invalid_config", CONTROL_PATH)
    try:
        text = raw.decode("utf-8")
        node = yaml.compose(text, Loader=yaml.SafeLoader)
        if node is not None and _has_duplicate_mapping_keys(node):
            raise _invalid_config()
        value = yaml.safe_load(text)
    except (UnicodeDecodeError, yaml.YAMLError):
        raise _invalid_config() from None

    if type(value) is not dict or set(value) != {"format", "kernel", "limits", "outputs"}:
        raise _invalid_config()
    if type(value["format"]) is not int or value["format"] != _FORMAT:
        raise _invalid_config()
    if value["kernel"] != KERNEL_PATH.as_posix():
        raise _invalid_config()

    limits = value["limits"]
    if type(limits) is not dict or set(limits) != {"max_lines", "target_lines", "max_bytes"}:
        raise _invalid_config()
    if any(type(limits[key]) is not int for key in ("max_lines", "target_lines", "max_bytes")):
        raise _invalid_config()
    if limits != {
        "max_lines": _MAX_LINES,
        "target_lines": _TARGET_LINES,
        "max_bytes": _MAX_BYTES,
    }:
        raise _invalid_config()

    outputs = value["outputs"]
    if type(outputs) is not dict or set(outputs) != set(_OUTPUTS):
        raise _invalid_config()
    if any(outputs[name] != target.as_posix() for name, target in _OUTPUTS.items()):
        raise _invalid_config()
    if len(set(outputs.values())) != len(outputs):
        raise _invalid_config()

    return AdapterConfig(
        format=_FORMAT,
        kernel=KERNEL_PATH,
        limits=AdapterLimits(_MAX_LINES, _TARGET_LINES, _MAX_BYTES),
        outputs=tuple(sorted(_OUTPUTS.items())),
    )


def _has_duplicate_mapping_keys(node: yaml.Node) -> bool:
    if isinstance(node, yaml.MappingNode):
        keys: set[str] = set()
        for key, value in node.value:
            if not isinstance(key, yaml.ScalarNode) or key.value in keys:
                return True
            keys.add(key.value)
            if _has_duplicate_mapping_keys(value):
                return True
        return False
    if isinstance(node, yaml.SequenceNode):
        return any(_has_duplicate_mapping_keys(item) for item in node.value)
    return False


def _validate_text_bytes(raw: bytes, code: str, path: PurePosixPath) -> None:
    try:
        raw.decode("utf-8")
    except UnicodeDecodeError:
        raise AdapterFailure((AdapterFinding(code, path, "source is not valid UTF-8"),)) from None
    if b"\r" in raw or not raw.endswith(b"\n") or raw.endswith(b"\n\n"):
        raise AdapterFailure(
            (AdapterFinding(code, path, "source must use LF and exactly one trailing newline"),)
        )


def _render_outputs(config: AdapterConfig, kernel: bytes) -> tuple[AdapterOutput, ...]:
    rendered: list[AdapterOutput] = []
    for name, target in sorted(config.outputs, key=lambda item: item[1].as_posix()):
        preamble = _PREAMBLES[name]
        payload = preamble + kernel
        line_count = payload.count(b"\n")
        byte_count = len(payload)
        if line_count > config.limits.max_lines or byte_count > config.limits.max_bytes:
            raise AdapterFailure(
                (
                    AdapterFinding(
                        "limit_exceeded",
                        target,
                        "rendered adapter exceeds a hard size limit",
                    ),
                )
            )
        rendered.append(
            AdapterOutput(
                name=name,
                target=target,
                preamble=preamble,
                payload=payload,
                sha256=_sha256(payload),
                line_count=line_count,
                byte_count=byte_count,
            )
        )
    return tuple(rendered)


def _invalid_config() -> AdapterFailure:
    return AdapterFailure(
        (AdapterFinding("invalid_config", CONTROL_PATH, "adapter control is not strict format 1"),)
    )


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()
