"""Build deterministic root-agent adapter plans from one canonical kernel."""

import errno
import hashlib
import json
import os
import stat
import tempfile
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

import yaml


CONTROL_PATH = PurePosixPath(".sdd/controls/adapters.yaml")
KERNEL_PATH = PurePosixPath(".sdd/adapters/root-kernel.md")
MANIFEST_PATH = PurePosixPath(".sdd/agent-adapters.generated.json")
RENDERER = "sdd.adapters.agent:v1"

_FORMAT = 1
_MAX_LINES = 280
_TARGET_LINES = 180
_MAX_BYTES = 16384
_OPEN_SUPPORTS_DIR_FD = os.open in os.supports_dir_fd
_WRITE_SUPPORTS_DIR_FD = (
    os.rename in os.supports_dir_fd
    and os.stat in os.supports_dir_fd
    and os.unlink in os.supports_dir_fd
    and os.stat in os.supports_follow_symlinks
)
_UNSAFE_PATH_ERRNOS = frozenset(
    {errno.ENOENT, errno.ENOTDIR, errno.ELOOP, errno.EISDIR, errno.ENXIO}
)
_OUTPUTS = {"claude": PurePosixPath("CLAUDE.md"), "codex": PurePosixPath("AGENTS.md")}
_PREAMBLES = {
    "claude": (
        b"<!-- Generated root adapter for Claude; do not edit this file directly. -->\n"
        b"<!-- Canonical sources: `.sdd/controls/adapters.yaml` and "
        b"`.sdd/adapters/root-kernel.md`. -->\n\n"
    ),
    "codex": (
        b"<!-- Generated root adapter for Codex; do not edit this file directly. -->\n"
        b"<!-- Canonical sources: `.sdd/controls/adapters.yaml` and "
        b"`.sdd/adapters/root-kernel.md`. -->\n\n"
    ),
}


@dataclass(frozen=True)
class AdapterLimits:
    max_lines: int
    target_lines: int
    max_bytes: int


@dataclass(frozen=True)
class AdapterConfig:
    format: int
    kernel: PurePosixPath
    limits: AdapterLimits
    outputs: tuple[tuple[str, PurePosixPath], ...]


@dataclass(frozen=True)
class AdapterOutput:
    name: str
    target: PurePosixPath
    preamble: bytes
    payload: bytes
    sha256: str
    line_count: int
    byte_count: int


@dataclass(frozen=True)
class AdapterPlan:
    format: int
    renderer: str
    config_sha256: str
    kernel_sha256: str
    outputs: tuple[AdapterOutput, ...]


@dataclass(frozen=True)
class AdapterManifest:
    format: int
    renderer: str
    adapter_format: int
    config_path: PurePosixPath
    config_sha256: str
    kernel_path: PurePosixPath
    kernel_sha256: str
    files: tuple[tuple[PurePosixPath, str, int, int, bool], ...]
    raw_bytes: bytes


@dataclass(frozen=True)
class AdapterFinding:
    code: str
    path: PurePosixPath | None
    message: str


class AdapterFailure(Exception):
    def __init__(self, findings: tuple[AdapterFinding, ...]):
        super().__init__("agent adapter planning failed")
        self.findings = findings


@dataclass(frozen=True)
class _RegularFileState:
    payload: bytes
    executable: bool
    device: int
    inode: int
    permissions: int


@dataclass(frozen=True)
class _DirectoryIdentity:
    resolved_path: Path
    device: int
    inode: int


@dataclass(frozen=True)
class _WritePreflight:
    repository_identity: _DirectoryIdentity
    sdd_identity: _DirectoryIdentity
    prior_manifest: AdapterManifest | None
    manifest_payload: bytes | None


@dataclass
class _PreparedAdapterFile:
    parent_fd: int
    temporary_name: str
    device: int
    inode: int
    owned: bool = True


def build_adapter_plan(root: Path) -> AdapterPlan:
    """Validate canonical inputs and render both root adapters in memory."""
    try:
        repository = _validated_repository_root(root)
        raw_config = _read_regular_file(repository, CONTROL_PATH)
        config = _load_config(raw_config)
        kernel = _read_regular_file(repository, config.kernel)
        _validate_text_bytes(kernel, "invalid_kernel", config.kernel)
        outputs = _render_outputs(config, kernel)
        return AdapterPlan(
            format=config.format,
            renderer=RENDERER,
            config_sha256=_sha256(raw_config),
            kernel_sha256=_sha256(kernel),
            outputs=outputs,
        )
    except AdapterFailure:
        raise
    except (OSError, RuntimeError, TypeError, ValueError, UnicodeError, yaml.YAMLError):
        raise AdapterFailure(
            (AdapterFinding("technical_block", None, "adapter plan could not be built safely"),)
        ) from None


def serialize_adapter_manifest(plan: AdapterPlan) -> bytes:
    """Serialize a complete adapter plan as canonical ownership JSON."""
    _validate_manifest_plan(plan)
    return _serialize_adapter_manifest_unchecked(plan)


def _serialize_adapter_manifest_unchecked(plan: AdapterPlan) -> bytes:
    payload = {
        "format": _FORMAT,
        "renderer": RENDERER,
        "adapter_format": plan.format,
        "config": {
            "path": CONTROL_PATH.as_posix(),
            "sha256": plan.config_sha256,
        },
        "kernel": {
            "path": KERNEL_PATH.as_posix(),
            "sha256": plan.kernel_sha256,
        },
        "files": [
            {
                "path": output.target.as_posix(),
                "sha256": output.sha256,
                "bytes": output.byte_count,
                "lines": output.line_count,
                "executable": False,
            }
            for output in plan.outputs
        ],
    }
    return (json.dumps(payload, sort_keys=True, indent=2) + "\n").encode("utf-8")


def load_adapter_manifest(root: Path) -> AdapterManifest:
    """Load the ownership manifest only when it is safe, strict, and canonical."""
    try:
        repository = _validated_repository_root(root)
        try:
            state = _read_regular_file_state(repository, MANIFEST_PATH)
        except AdapterFailure as failure:
            if all(finding.code == "unsafe_path" for finding in failure.findings):
                raise _invalid_manifest() from None
            raise
        assert state is not None
        return _parse_adapter_manifest(state.payload)
    except AdapterFailure:
        raise
    except (OSError, RuntimeError, TypeError, ValueError, UnicodeError, json.JSONDecodeError):
        raise AdapterFailure(
            (
                AdapterFinding(
                    "technical_block",
                    MANIFEST_PATH,
                    "adapter manifest could not be loaded safely",
                ),
            )
        ) from None


def check_agent_adapters(root: Path, plan: AdapterPlan) -> tuple[AdapterFinding, ...]:
    """Return manifest and live-output parity findings without mutation."""
    try:
        return _check_agent_adapters(root, plan)
    except AdapterFailure as failure:
        return _sorted_findings(list(failure.findings))
    except (OSError, RuntimeError, TypeError, ValueError, UnicodeError):
        return (
            AdapterFinding(
                "technical_block",
                None,
                "agent adapters could not be checked safely",
            ),
        )


def write_agent_adapters(root: Path, plan: AdapterPlan) -> None:
    """Safely converge the two fixed root adapters and commit ownership last."""
    try:
        _write_agent_adapters(root, plan)
    except AdapterFailure:
        raise
    except (OSError, RuntimeError, TypeError, ValueError, UnicodeError):
        raise AdapterFailure(
            (
                AdapterFinding(
                    "technical_block",
                    None,
                    "agent adapters could not be written safely",
                ),
            )
        ) from None


def _write_agent_adapters(root: Path, plan: AdapterPlan) -> None:
    _validate_manifest_plan(plan)
    repository = _validated_repository_root(root)
    desired_manifest = _serialize_adapter_manifest_unchecked(plan)
    preflight = _preflight_adapter_write(repository, plan)
    _require_safe_write_support()
    prior_files = (
        {}
        if preflight.prior_manifest is None
        else {item[0]: item for item in preflight.prior_manifest.files}
    )

    for output in plan.outputs:
        target = repository / output.target
        _recheck_write_parents(repository, preflight)
        live = _read_regular_file_state(repository, output.target, allow_missing=True)
        if not _accepted_output_state(live, output, prior_files.get(output.target)):
            raise AdapterFailure(
                (
                    AdapterFinding(
                        "conflicting_output",
                        output.target,
                        "adapter output changed after preflight",
                    ),
                )
            )
        if _live_matches_output(live, output):
            continue

        prepared = _prepare_adapter_file(
            target,
            output.payload,
            preflight.repository_identity,
            None,
        )
        try:
            _validate_prepared_file(prepared, output.payload, output.target)
            _recheck_write_parents(repository, preflight)
            _validate_pinned_directory(
                prepared.parent_fd,
                preflight.repository_identity,
                None,
            )
            live = _read_regular_file_state_at(
                prepared.parent_fd,
                output.target.name,
                output.target,
                allow_missing=True,
            )
            if not _accepted_output_state(live, output, prior_files.get(output.target)):
                raise AdapterFailure(
                    (
                        AdapterFinding(
                            "conflicting_output",
                            output.target,
                            "adapter output changed during temporary preparation",
                        ),
                    )
                )
            if not _live_matches_output(live, output):
                _commit_prepared_file(prepared, output.target.name)
                committed = _read_regular_file_state_at(
                    prepared.parent_fd,
                    output.target.name,
                    output.target,
                )
                if not _live_matches_output(committed, output):
                    raise AdapterFailure(
                        (
                            AdapterFinding(
                                "conflicting_output",
                                output.target,
                                "committed adapter output failed immediate verification",
                            ),
                        )
                    )
                _recheck_write_parents(repository, preflight)
        finally:
            _discard_prepared_file(prepared)

    verification_findings = _verify_written_outputs(repository, plan)
    if verification_findings:
        raise AdapterFailure(verification_findings)

    _recheck_write_parents(repository, preflight)
    live_manifest = _read_manifest_payload(repository)
    if not _accepted_manifest_payload(live_manifest, desired_manifest, preflight):
        raise AdapterFailure(
            (
                AdapterFinding(
                    "invalid_manifest",
                    MANIFEST_PATH,
                    "adapter manifest changed after preflight",
                ),
            )
        )

    prepared_manifest: _PreparedAdapterFile | None = None
    sdd_fd: int | None = None
    root_fd: int | None = None
    try:
        if live_manifest != desired_manifest:
            prepared_manifest = _prepare_adapter_file(
                repository / MANIFEST_PATH,
                desired_manifest,
                preflight.sdd_identity,
                MANIFEST_PATH.parent,
            )
            _validate_prepared_file(
                prepared_manifest,
                desired_manifest,
                MANIFEST_PATH,
            )
            sdd_fd = prepared_manifest.parent_fd
        else:
            sdd_fd = _open_pinned_directory(
                repository / MANIFEST_PATH.parent,
                preflight.sdd_identity,
                MANIFEST_PATH.parent,
            )
        root_fd = _open_pinned_directory(
            repository,
            preflight.repository_identity,
            None,
        )

        _recheck_write_parents(repository, preflight)
        _validate_pinned_directory(root_fd, preflight.repository_identity, None)
        _validate_pinned_directory(sdd_fd, preflight.sdd_identity, MANIFEST_PATH.parent)
        final_output_findings = _verify_outputs_from_parent_fd(root_fd, plan)
        if final_output_findings:
            raise AdapterFailure(final_output_findings)
        final_manifest = _read_manifest_state_at(
            sdd_fd,
            allow_missing=True,
        )
        final_manifest_payload = None if final_manifest is None else final_manifest.payload
        if (
            (final_manifest is not None and final_manifest.executable)
            or not _accepted_manifest_payload(
                final_manifest_payload,
                desired_manifest,
                preflight,
            )
        ):
            raise AdapterFailure(
                (
                    AdapterFinding(
                        "invalid_manifest",
                        MANIFEST_PATH,
                        "adapter manifest changed during temporary preparation",
                    ),
                )
            )

        if final_manifest_payload != desired_manifest:
            if prepared_manifest is None:
                raise AdapterFailure(
                    (
                        AdapterFinding(
                            "invalid_manifest",
                            MANIFEST_PATH,
                            "desired adapter manifest changed before final verification",
                        ),
                    )
                )
            _commit_prepared_file(prepared_manifest, MANIFEST_PATH.name)

        committed_manifest = _read_manifest_state_at(
            sdd_fd,
        )
        if (
            committed_manifest is None
            or committed_manifest.payload != desired_manifest
            or committed_manifest.executable
        ):
            raise AdapterFailure(
                (
                    AdapterFinding(
                        "invalid_manifest",
                        MANIFEST_PATH,
                        "committed adapter manifest failed immediate verification",
                    ),
                )
            )
        post_commit_findings = _verify_outputs_from_parent_fd(root_fd, plan)
        if post_commit_findings:
            raise AdapterFailure(post_commit_findings)
        _recheck_write_parents(repository, preflight)
    finally:
        if root_fd is not None:
            os.close(root_fd)
        if prepared_manifest is not None:
            _discard_prepared_file(prepared_manifest)
        elif sdd_fd is not None:
            os.close(sdd_fd)


def _check_agent_adapters(root: Path, plan: AdapterPlan) -> tuple[AdapterFinding, ...]:
    repository = _validated_repository_root(root)
    plan_findings, inventory_is_safe = _manifest_plan_findings(plan)
    if not inventory_is_safe:
        return _sorted_findings(list(plan_findings))
    findings = list(plan_findings)
    desired_manifest = (
        _manifest_from_plan_unchecked(plan)
        if all(finding.code == "limit_exceeded" for finding in plan_findings)
        else None
    )
    prior: AdapterManifest | None
    try:
        prior = load_adapter_manifest(repository)
    except AdapterFailure as failure:
        findings.extend(failure.findings)
        prior = None

    if prior is not None and desired_manifest is not None:
        stale_source = False
        if prior.config_sha256 != plan.config_sha256:
            stale_source = True
            findings.append(
                AdapterFinding(
                    "invalid_source",
                    CONTROL_PATH,
                    "manifest records a different adapter control digest",
                )
            )
        if prior.kernel_sha256 != plan.kernel_sha256:
            stale_source = True
            findings.append(
                AdapterFinding(
                    "invalid_source",
                    KERNEL_PATH,
                    "manifest records a different kernel digest",
                )
            )
        if not stale_source and prior != desired_manifest:
            findings.append(
                AdapterFinding(
                    "invalid_manifest",
                    MANIFEST_PATH,
                    "manifest does not completely match the desired adapter plan",
                )
            )

    desired_files = (
        {} if desired_manifest is None else {item[0]: item for item in desired_manifest.files}
    )
    prior_files = {} if prior is None else {item[0]: item for item in prior.files}
    for target in sorted(_OUTPUTS.values(), key=lambda path: path.as_posix()):
        desired = desired_files.get(target)
        try:
            live = _read_regular_file_state(repository, target, allow_missing=True)
        except AdapterFailure as failure:
            findings.extend(failure.findings)
            continue
        if live is None:
            findings.append(AdapterFinding("missing_output", target, "adapter output is missing"))
            continue
        if desired is None:
            continue
        if _live_matches_manifest_file(live, desired):
            continue
        owned = prior_files.get(target)
        if owned is not None and _live_matches_manifest_file(live, owned):
            findings.append(
                AdapterFinding("stale_output", target, "adapter output matches prior ownership")
            )
        else:
            findings.append(
                AdapterFinding(
                    "conflicting_output",
                    target,
                    "adapter output matches neither desired nor prior ownership",
                )
            )
    return _sorted_findings(findings)


def _preflight_adapter_write(repository: Path, plan: AdapterPlan) -> _WritePreflight:
    findings: list[AdapterFinding] = []
    repository_identity: _DirectoryIdentity | None = None
    sdd_identity: _DirectoryIdentity | None = None
    try:
        repository_identity = _capture_directory_identity(repository, None)
    except AdapterFailure as failure:
        findings.extend(failure.findings)
    try:
        sdd_identity = _capture_directory_identity(
            repository / MANIFEST_PATH.parent,
            MANIFEST_PATH.parent,
        )
    except AdapterFailure as failure:
        findings.extend(failure.findings)

    prior_manifest: AdapterManifest | None = None
    manifest_payload: bytes | None = None
    try:
        manifest_state = _read_regular_file_state(
            repository,
            MANIFEST_PATH,
            allow_missing=True,
        )
        if manifest_state is not None:
            manifest_payload = manifest_state.payload
            if manifest_state.executable:
                raise _invalid_manifest()
            prior_manifest = _parse_adapter_manifest(manifest_state.payload)
    except AdapterFailure as failure:
        findings.extend(_writer_manifest_findings(failure))

    prior_files = (
        {} if prior_manifest is None else {item[0]: item for item in prior_manifest.files}
    )
    for output in plan.outputs:
        try:
            live = _read_regular_file_state(
                repository,
                output.target,
                allow_missing=True,
            )
        except AdapterFailure as failure:
            findings.extend(failure.findings)
            continue
        if not _accepted_output_state(live, output, prior_files.get(output.target)):
            findings.append(
                AdapterFinding(
                    "conflicting_output",
                    output.target,
                    "adapter output matches neither desired nor prior ownership",
                )
            )

    if findings:
        raise AdapterFailure(_sorted_findings(findings))
    assert repository_identity is not None
    assert sdd_identity is not None
    return _WritePreflight(
        repository_identity=repository_identity,
        sdd_identity=sdd_identity,
        prior_manifest=prior_manifest,
        manifest_payload=manifest_payload,
    )


def _capture_directory_identity(
    path: Path,
    relative: PurePosixPath | None,
) -> _DirectoryIdentity:
    try:
        before = path.lstat()
        if stat.S_ISLNK(before.st_mode) or not stat.S_ISDIR(before.st_mode):
            raise AdapterFailure(
                (
                    AdapterFinding(
                        "unsafe_path",
                        relative,
                        "write parent is not a safe directory",
                    ),
                )
            )
        resolved = path.resolve(strict=True)
        after = path.lstat()
    except AdapterFailure:
        raise
    except OSError as error:
        code = "unsafe_path" if error.errno in _UNSAFE_PATH_ERRNOS else "technical_block"
        message = (
            "write parent is unavailable or unsafe"
            if code == "unsafe_path"
            else "write parent identity could not be inspected"
        )
        raise AdapterFailure(
            (
                AdapterFinding(
                    code,
                    relative,
                    message,
                ),
            )
        ) from None
    except RuntimeError:
        raise AdapterFailure(
            (
                AdapterFinding(
                    "unsafe_path",
                    relative,
                    "write parent is unavailable or unsafe",
                ),
            )
        ) from None
    if (
        stat.S_ISLNK(after.st_mode)
        or not stat.S_ISDIR(after.st_mode)
        or before.st_dev != after.st_dev
        or before.st_ino != after.st_ino
    ):
        raise AdapterFailure(
            (
                AdapterFinding(
                    "unsafe_path",
                    relative,
                    "write parent changed during inspection",
                ),
            )
        )
    return _DirectoryIdentity(
        resolved_path=resolved,
        device=after.st_dev,
        inode=after.st_ino,
    )


def _recheck_write_parents(repository: Path, preflight: _WritePreflight) -> None:
    current_repository = _capture_directory_identity(repository, None)
    if current_repository != preflight.repository_identity:
        raise AdapterFailure(
            (
                AdapterFinding(
                    "unsafe_path",
                    None,
                    "repository root changed after preflight",
                ),
            )
        )
    current_sdd = _capture_directory_identity(
        repository / MANIFEST_PATH.parent,
        MANIFEST_PATH.parent,
    )
    if current_sdd != preflight.sdd_identity:
        raise AdapterFailure(
            (
                AdapterFinding(
                    "unsafe_path",
                    MANIFEST_PATH.parent,
                    ".sdd directory changed after preflight",
                ),
            )
        )


def _accepted_output_state(
    live: _RegularFileState | None,
    desired: AdapterOutput,
    prior: tuple[PurePosixPath, str, int, int, bool] | None,
) -> bool:
    return (
        live is None
        or _live_matches_output(live, desired)
        or (prior is not None and _live_matches_manifest_file(live, prior))
    )


def _live_matches_output(live: _RegularFileState | None, output: AdapterOutput) -> bool:
    return live is not None and live.payload == output.payload and not live.executable


def _verify_written_outputs(
    repository: Path,
    plan: AdapterPlan,
) -> tuple[AdapterFinding, ...]:
    findings: list[AdapterFinding] = []
    for output in plan.outputs:
        try:
            live = _read_regular_file_state(
                repository,
                output.target,
                allow_missing=True,
            )
        except AdapterFailure as failure:
            findings.extend(failure.findings)
            continue
        if live is None:
            findings.append(
                AdapterFinding("missing_output", output.target, "adapter output is missing")
            )
        elif not _live_matches_output(live, output):
            findings.append(
                AdapterFinding(
                    "conflicting_output",
                    output.target,
                    "adapter output changed during final verification",
                )
            )
    return _sorted_findings(findings)


def _verify_outputs_from_parent_fd(
    repository_fd: int,
    plan: AdapterPlan,
) -> tuple[AdapterFinding, ...]:
    findings: list[AdapterFinding] = []
    for output in plan.outputs:
        try:
            live = _read_regular_file_state_at(
                repository_fd,
                output.target.name,
                output.target,
                allow_missing=True,
            )
        except AdapterFailure as failure:
            findings.extend(failure.findings)
            continue
        if live is None:
            findings.append(
                AdapterFinding("missing_output", output.target, "adapter output is missing")
            )
        elif not _live_matches_output(live, output):
            findings.append(
                AdapterFinding(
                    "conflicting_output",
                    output.target,
                    "adapter output changed at the manifest commit boundary",
                )
            )
    return _sorted_findings(findings)


def _read_manifest_payload(repository: Path) -> bytes | None:
    try:
        state = _read_regular_file_state(repository, MANIFEST_PATH, allow_missing=True)
    except AdapterFailure as failure:
        raise AdapterFailure(_writer_manifest_findings(failure)) from None
    if state is None:
        return None
    if state.executable:
        raise _invalid_manifest()
    return state.payload


def _read_manifest_state_at(
    sdd_fd: int,
    *,
    allow_missing: bool = False,
) -> _RegularFileState | None:
    try:
        return _read_regular_file_state_at(
            sdd_fd,
            MANIFEST_PATH.name,
            MANIFEST_PATH,
            allow_missing=allow_missing,
        )
    except AdapterFailure as failure:
        raise AdapterFailure(_writer_manifest_findings(failure)) from None


def _accepted_manifest_payload(
    live: bytes | None,
    desired: bytes,
    preflight: _WritePreflight,
) -> bool:
    return live in {None, desired, preflight.manifest_payload}


def _writer_manifest_findings(
    failure: AdapterFailure,
) -> tuple[AdapterFinding, ...]:
    if any(finding.code == "technical_block" for finding in failure.findings):
        return failure.findings
    return _invalid_manifest().findings


def _require_safe_write_support() -> None:
    required_flags = ("O_DIRECTORY", "O_NOFOLLOW", "O_NONBLOCK")
    if (
        not _OPEN_SUPPORTS_DIR_FD
        or not _WRITE_SUPPORTS_DIR_FD
        or any(not hasattr(os, name) for name in required_flags)
    ):
        raise AdapterFailure(
            (
                AdapterFinding(
                    "technical_block",
                    None,
                    "safe descriptor-relative replacement is unavailable",
                ),
            )
        )


def _open_pinned_directory(
    path: Path,
    expected: _DirectoryIdentity,
    relative: PurePosixPath | None,
) -> int:
    directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
    close_on_exec = getattr(os, "O_CLOEXEC", 0)
    try:
        directory_fd = os.open(path, directory_flags | close_on_exec)
    except OSError as error:
        raise _inspection_failure(relative, error) from None
    try:
        _validate_pinned_directory(directory_fd, expected, relative)
        return directory_fd
    except BaseException:
        os.close(directory_fd)
        raise


def _validate_pinned_directory(
    directory_fd: int,
    expected: _DirectoryIdentity,
    relative: PurePosixPath | None,
) -> None:
    try:
        info = os.fstat(directory_fd)
    except OSError:
        raise AdapterFailure(
            (
                AdapterFinding(
                    "technical_block",
                    relative,
                    "pinned write parent could not be inspected",
                ),
            )
        ) from None
    if (
        not stat.S_ISDIR(info.st_mode)
        or info.st_dev != expected.device
        or info.st_ino != expected.inode
    ):
        raise AdapterFailure(
            (
                AdapterFinding(
                    "unsafe_path",
                    relative,
                    "pinned write parent does not match preflight identity",
                ),
            )
        )


def _prepare_adapter_file(
    path: Path,
    payload: bytes,
    expected_parent: _DirectoryIdentity,
    parent_relative: PurePosixPath | None,
) -> _PreparedAdapterFile:
    parent_fd = _open_pinned_directory(path.parent, expected_parent, parent_relative)
    prepared: _PreparedAdapterFile | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as temporary:
            info = os.fstat(temporary.fileno())
            prepared = _PreparedAdapterFile(
                parent_fd=parent_fd,
                temporary_name=Path(temporary.name).name,
                device=info.st_dev,
                inode=info.st_ino,
            )
            temporary.write(payload)
            temporary.flush()
            os.fsync(temporary.fileno())
            os.fchmod(temporary.fileno(), 0o644)
            os.fsync(temporary.fileno())
        _validate_prepared_file(prepared, payload, PurePosixPath(path.name))
        return prepared
    except BaseException:
        if prepared is not None:
            _discard_prepared_file(prepared)
        else:
            os.close(parent_fd)
        raise


def _validate_prepared_file(
    prepared: _PreparedAdapterFile,
    payload: bytes,
    relative: PurePosixPath,
) -> None:
    state = _read_regular_file_state_at(
        prepared.parent_fd,
        prepared.temporary_name,
        relative,
    )
    if (
        state is None
        or state.device != prepared.device
        or state.inode != prepared.inode
        or state.payload != payload
        or state.permissions != 0o644
    ):
        raise AdapterFailure(
            (
                AdapterFinding(
                    "unsafe_path",
                    relative,
                    "prepared adapter temporary changed before commit",
                ),
            )
        )


def _commit_prepared_file(
    prepared: _PreparedAdapterFile,
    destination_name: str,
) -> None:
    os.replace(
        prepared.temporary_name,
        destination_name,
        src_dir_fd=prepared.parent_fd,
        dst_dir_fd=prepared.parent_fd,
    )
    prepared.owned = False


def _discard_prepared_file(prepared: _PreparedAdapterFile) -> None:
    try:
        if not prepared.owned:
            return
        try:
            info = os.stat(
                prepared.temporary_name,
                dir_fd=prepared.parent_fd,
                follow_symlinks=False,
            )
        except FileNotFoundError:
            return
        if (
            stat.S_ISREG(info.st_mode)
            and info.st_dev == prepared.device
            and info.st_ino == prepared.inode
        ):
            os.unlink(prepared.temporary_name, dir_fd=prepared.parent_fd)
            prepared.owned = False
    finally:
        os.close(prepared.parent_fd)


def _validated_repository_root(root: Path) -> Path:
    repository = Path(root)
    try:
        mode = repository.lstat().st_mode
    except OSError as error:
        code = "unsafe_path" if error.errno in _UNSAFE_PATH_ERRNOS else "technical_block"
        message = (
            "repository root path is missing or unsafe"
            if code == "unsafe_path"
            else "repository root could not be inspected"
        )
        raise AdapterFailure(
            (AdapterFinding(code, None, message),)
        ) from None
    if stat.S_ISLNK(mode) or not stat.S_ISDIR(mode):
        raise AdapterFailure(
            (AdapterFinding("unsafe_path", None, "repository root is not a safe directory"),)
        )
    return repository


def _read_regular_file(repository: Path, relative: PurePosixPath) -> bytes:
    state = _read_regular_file_state(repository, relative)
    assert state is not None
    return state.payload


def _read_regular_file_state(
    repository: Path,
    relative: PurePosixPath,
    *,
    allow_missing: bool = False,
) -> _RegularFileState | None:
    required_flags = ("O_DIRECTORY", "O_NOFOLLOW", "O_NONBLOCK")
    if not _OPEN_SUPPORTS_DIR_FD or any(not hasattr(os, name) for name in required_flags):
        raise AdapterFailure(
            (
                AdapterFinding(
                    "technical_block",
                    relative,
                    "safe descriptor traversal is unavailable",
                ),
            )
        )

    directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
    file_flags = os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK
    close_on_exec = getattr(os, "O_CLOEXEC", 0)
    opened_fds: list[int] = []
    try:
        directory_fd = os.open(repository, directory_flags | close_on_exec)
        opened_fds.append(directory_fd)
        if not stat.S_ISDIR(os.fstat(directory_fd).st_mode):
            raise AdapterFailure(
                (AdapterFinding("unsafe_path", relative, "repository root is not a directory"),)
            )

        for part in relative.parts[:-1]:
            directory_fd = os.open(
                part,
                directory_flags | close_on_exec,
                dir_fd=directory_fd,
            )
            opened_fds.append(directory_fd)
            if not stat.S_ISDIR(os.fstat(directory_fd).st_mode):
                raise AdapterFailure(
                    (AdapterFinding("unsafe_path", relative, "file parent is not a directory"),)
                )

        try:
            file_fd = os.open(
                relative.name,
                file_flags | close_on_exec,
                dir_fd=directory_fd,
            )
        except FileNotFoundError:
            if allow_missing:
                return None
            raise
        opened_fds.append(file_fd)
        file_info = os.fstat(file_fd)
        file_mode = file_info.st_mode
        if not stat.S_ISREG(file_mode):
            raise AdapterFailure(
                (AdapterFinding("unsafe_path", relative, "path is not a regular file"),)
            )
        chunks: list[bytes] = []
        while chunk := os.read(file_fd, 65536):
            chunks.append(chunk)
        return _RegularFileState(
            payload=b"".join(chunks),
            executable=bool(file_mode & 0o111),
            device=file_info.st_dev,
            inode=file_info.st_ino,
            permissions=stat.S_IMODE(file_mode),
        )
    except AdapterFailure:
        raise
    except OSError as error:
        raise _inspection_failure(relative, error) from None
    finally:
        for opened_fd in reversed(opened_fds):
            os.close(opened_fd)


def _read_regular_file_state_at(
    parent_fd: int,
    name: str,
    relative: PurePosixPath,
    *,
    allow_missing: bool = False,
) -> _RegularFileState | None:
    file_flags = os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK
    close_on_exec = getattr(os, "O_CLOEXEC", 0)
    try:
        try:
            file_fd = os.open(
                name,
                file_flags | close_on_exec,
                dir_fd=parent_fd,
            )
        except FileNotFoundError:
            if allow_missing:
                return None
            raise
        try:
            info = os.fstat(file_fd)
            if not stat.S_ISREG(info.st_mode):
                raise AdapterFailure(
                    (AdapterFinding("unsafe_path", relative, "path is not a regular file"),)
                )
            chunks: list[bytes] = []
            while chunk := os.read(file_fd, 65536):
                chunks.append(chunk)
            return _RegularFileState(
                payload=b"".join(chunks),
                executable=bool(info.st_mode & 0o111),
                device=info.st_dev,
                inode=info.st_ino,
                permissions=stat.S_IMODE(info.st_mode),
            )
        finally:
            os.close(file_fd)
    except AdapterFailure:
        raise
    except OSError as error:
        raise _inspection_failure(relative, error) from None


def _inspection_failure(
    relative: PurePosixPath | None,
    error: OSError,
) -> AdapterFailure:
    if error.errno in _UNSAFE_PATH_ERRNOS:
        return AdapterFailure(
            (AdapterFinding("unsafe_path", relative, "path is missing, unsafe, or not regular"),)
        )
    return AdapterFailure(
        (
            AdapterFinding(
                "technical_block",
                relative,
                "file state could not be inspected safely",
            ),
        )
    )


def _load_config(raw: bytes) -> AdapterConfig:
    _validate_text_bytes(raw, "invalid_config", CONTROL_PATH)
    try:
        text = raw.decode("utf-8")
        node = yaml.compose(text, Loader=yaml.SafeLoader)
        if node is not None and _has_duplicate_mapping_keys(node):
            raise _invalid_config()
        value = yaml.safe_load(text)
    except (UnicodeDecodeError, yaml.YAMLError):
        raise _invalid_config() from None

    if type(value) is not dict or set(value) != {"format", "kernel", "limits", "outputs"}:
        raise _invalid_config()
    if type(value["format"]) is not int or value["format"] != _FORMAT:
        raise _invalid_config()
    if value["kernel"] != KERNEL_PATH.as_posix():
        raise _invalid_config()

    limits = value["limits"]
    if type(limits) is not dict or set(limits) != {"max_lines", "target_lines", "max_bytes"}:
        raise _invalid_config()
    if any(type(limits[key]) is not int for key in ("max_lines", "target_lines", "max_bytes")):
        raise _invalid_config()
    if limits != {
        "max_lines": _MAX_LINES,
        "target_lines": _TARGET_LINES,
        "max_bytes": _MAX_BYTES,
    }:
        raise _invalid_config()

    outputs = value["outputs"]
    if type(outputs) is not dict or set(outputs) != set(_OUTPUTS):
        raise _invalid_config()
    if any(outputs[name] != target.as_posix() for name, target in _OUTPUTS.items()):
        raise _invalid_config()
    if len(set(outputs.values())) != len(outputs):
        raise _invalid_config()

    return AdapterConfig(
        format=_FORMAT,
        kernel=KERNEL_PATH,
        limits=AdapterLimits(_MAX_LINES, _TARGET_LINES, _MAX_BYTES),
        outputs=tuple(sorted(_OUTPUTS.items())),
    )


def _has_duplicate_mapping_keys(node: yaml.Node) -> bool:
    if isinstance(node, yaml.MappingNode):
        keys: set[str] = set()
        for key, value in node.value:
            if not isinstance(key, yaml.ScalarNode) or key.value in keys:
                return True
            keys.add(key.value)
            if _has_duplicate_mapping_keys(value):
                return True
        return False
    if isinstance(node, yaml.SequenceNode):
        return any(_has_duplicate_mapping_keys(item) for item in node.value)
    return False


def _validate_text_bytes(raw: bytes, code: str, path: PurePosixPath) -> None:
    try:
        raw.decode("utf-8")
    except UnicodeDecodeError:
        raise AdapterFailure((AdapterFinding(code, path, "source is not valid UTF-8"),)) from None
    if b"\r" in raw or not raw.endswith(b"\n") or raw.endswith(b"\n\n"):
        raise AdapterFailure(
            (AdapterFinding(code, path, "source must use LF and exactly one trailing newline"),)
        )


def _render_outputs(config: AdapterConfig, kernel: bytes) -> tuple[AdapterOutput, ...]:
    rendered: list[AdapterOutput] = []
    for name, target in sorted(config.outputs, key=lambda item: item[1].as_posix()):
        preamble = _PREAMBLES[name]
        payload = preamble + kernel
        line_count = payload.count(b"\n")
        byte_count = len(payload)
        if line_count > config.limits.max_lines or byte_count > config.limits.max_bytes:
            raise AdapterFailure(
                (
                    AdapterFinding(
                        "limit_exceeded",
                        target,
                        "rendered adapter exceeds a hard size limit",
                    ),
                )
            )
        rendered.append(
            AdapterOutput(
                name=name,
                target=target,
                preamble=preamble,
                payload=payload,
                sha256=_sha256(payload),
                line_count=line_count,
                byte_count=byte_count,
            )
        )
    return tuple(rendered)


def _invalid_config() -> AdapterFailure:
    return AdapterFailure(
        (AdapterFinding("invalid_config", CONTROL_PATH, "adapter control is not strict format 1"),)
    )


def _invalid_manifest() -> AdapterFailure:
    return AdapterFailure(
        (
            AdapterFinding(
                "invalid_manifest",
                MANIFEST_PATH,
                "adapter manifest is missing, unsafe, or invalid",
            ),
        )
    )


def _parse_adapter_manifest(raw: bytes) -> AdapterManifest:
    try:
        value = json.loads(raw.decode("utf-8"), object_pairs_hook=_unique_json_object)
    except (UnicodeDecodeError, ValueError, json.JSONDecodeError):
        raise _invalid_manifest() from None

    if type(value) is not dict or set(value) != {
        "format",
        "renderer",
        "adapter_format",
        "config",
        "kernel",
        "files",
    }:
        raise _invalid_manifest()
    if type(value["format"]) is not int or value["format"] != _FORMAT:
        raise _invalid_manifest()
    if value["renderer"] != RENDERER:
        raise _invalid_manifest()
    if type(value["adapter_format"]) is not int or value["adapter_format"] != _FORMAT:
        raise _invalid_manifest()

    config_path, config_sha256 = _manifest_source(
        value["config"],
        CONTROL_PATH,
    )
    kernel_path, kernel_sha256 = _manifest_source(
        value["kernel"],
        KERNEL_PATH,
    )
    if type(value["files"]) is not list:
        raise _invalid_manifest()
    files = tuple(_manifest_file(item) for item in value["files"])
    if tuple(item[0] for item in files) != tuple(
        sorted(_OUTPUTS.values(), key=lambda path: path.as_posix())
    ):
        raise _invalid_manifest()
    canonical = (json.dumps(value, sort_keys=True, indent=2) + "\n").encode("utf-8")
    if raw != canonical:
        raise _invalid_manifest()
    return AdapterManifest(
        format=_FORMAT,
        renderer=RENDERER,
        adapter_format=_FORMAT,
        config_path=config_path,
        config_sha256=config_sha256,
        kernel_path=kernel_path,
        kernel_sha256=kernel_sha256,
        files=files,
        raw_bytes=raw,
    )


def _manifest_source(value: object, expected_path: PurePosixPath) -> tuple[PurePosixPath, str]:
    if type(value) is not dict or set(value) != {"path", "sha256"}:
        raise _invalid_manifest()
    path = _manifest_path(value["path"])
    if path != expected_path or not _is_sha256(value["sha256"]):
        raise _invalid_manifest()
    return path, value["sha256"]


def _manifest_file(value: object) -> tuple[PurePosixPath, str, int, int, bool]:
    if type(value) is not dict or set(value) != {
        "path",
        "sha256",
        "bytes",
        "lines",
        "executable",
    }:
        raise _invalid_manifest()
    path = _manifest_path(value["path"])
    if not _is_sha256(value["sha256"]):
        raise _invalid_manifest()
    if type(value["bytes"]) is not int or value["bytes"] < 0:
        raise _invalid_manifest()
    if type(value["lines"]) is not int or value["lines"] < 0:
        raise _invalid_manifest()
    if value["executable"] is not False:
        raise _invalid_manifest()
    return (
        path,
        value["sha256"],
        value["bytes"],
        value["lines"],
        False,
    )


def _manifest_path(value: object) -> PurePosixPath:
    if type(value) is not str or not value or "\\" in value or "\x00" in value:
        raise _invalid_manifest()
    try:
        os.fsencode(value)
    except (ValueError, UnicodeError):
        raise _invalid_manifest() from None
    path = PurePosixPath(value)
    if path.is_absolute() or path.as_posix() != value or any(
        part in ("", ".", "..") for part in path.parts
    ):
        raise _invalid_manifest()
    return path


def _unique_json_object(pairs):
    value = {}
    for key, item in pairs:
        if key in value:
            raise ValueError("duplicate JSON object key")
        value[key] = item
    return value


def _validate_manifest_plan(plan: AdapterPlan) -> None:
    findings, _ = _manifest_plan_findings(plan)
    if findings:
        raise AdapterFailure(_sorted_findings(list(findings)))


def _manifest_plan_findings(
    plan: AdapterPlan,
) -> tuple[tuple[AdapterFinding, ...], bool]:
    expected_targets = tuple(sorted(_OUTPUTS.values(), key=lambda path: path.as_posix()))
    if type(plan) is not AdapterPlan:
        return (
            (AdapterFinding("invalid_source", None, "adapter plan is incomplete or invalid"),),
            False,
        )
    if (
        type(plan.outputs) is not tuple
        or len(plan.outputs) != len(expected_targets)
        or any(type(output) is not AdapterOutput for output in plan.outputs)
        or any(type(output.target) is not PurePosixPath for output in plan.outputs)
        or tuple(output.target for output in plan.outputs) != expected_targets
    ):
        return (
            (AdapterFinding("invalid_source", None, "adapter plan inventory is unsafe"),),
            False,
        )

    findings: list[AdapterFinding] = []
    if (
        type(plan.format) is not int
        or plan.format != _FORMAT
        or plan.renderer != RENDERER
        or not _is_sha256(plan.config_sha256)
        or not _is_sha256(plan.kernel_sha256)
    ):
        findings.append(
            AdapterFinding("invalid_source", None, "adapter plan is incomplete or invalid")
        )
    for output in plan.outputs:
        if (
            type(output.payload) is not bytes
            or not _is_sha256(output.sha256)
            or output.sha256 != _sha256(output.payload)
            or type(output.byte_count) is not int
            or output.byte_count != len(output.payload)
            or type(output.line_count) is not int
            or output.line_count != output.payload.count(b"\n")
        ):
            findings.append(
                AdapterFinding("invalid_source", output.target, "adapter plan output is invalid")
            )
        if (
            type(output.line_count) is int
            and type(output.byte_count) is int
            and (output.line_count > _MAX_LINES or output.byte_count > _MAX_BYTES)
        ):
            findings.append(
                AdapterFinding(
                    "limit_exceeded",
                    output.target,
                    "rendered adapter exceeds a hard size limit",
                )
            )
    return tuple(findings), True


def _manifest_from_plan_unchecked(plan: AdapterPlan) -> AdapterManifest:
    raw = _serialize_adapter_manifest_unchecked(plan)
    return AdapterManifest(
        format=_FORMAT,
        renderer=RENDERER,
        adapter_format=plan.format,
        config_path=CONTROL_PATH,
        config_sha256=plan.config_sha256,
        kernel_path=KERNEL_PATH,
        kernel_sha256=plan.kernel_sha256,
        files=tuple(
            (
                output.target,
                output.sha256,
                output.byte_count,
                output.line_count,
                False,
            )
            for output in plan.outputs
        ),
        raw_bytes=raw,
    )


def _live_matches_manifest_file(
    live: _RegularFileState,
    manifest_file: tuple[PurePosixPath, str, int, int, bool],
) -> bool:
    _, digest, byte_count, line_count, executable = manifest_file
    return (
        _sha256(live.payload) == digest
        and len(live.payload) == byte_count
        and live.payload.count(b"\n") == line_count
        and live.executable is executable
    )


def _is_sha256(value: object) -> bool:
    return (
        type(value) is str
        and len(value) == 64
        and all(character in "0123456789abcdef" for character in value)
    )


def _sorted_findings(findings: list[AdapterFinding]) -> tuple[AdapterFinding, ...]:
    return tuple(
        sorted(
            findings,
            key=lambda finding: (
                finding.path.as_posix() if finding.path is not None else "",
                finding.code,
            ),
        )
    )


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()
